"""ai suggestions

Revision ID: e7b4f5101c31
Revises: 8e9937cee674
Create Date: 2026-10-05 21:03:49.268811
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e7b4f5101c31'
down_revision: Union[str, None] = '8e9937cee674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('openai', 'rules', name='suggestionsource', native_enum=False, length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('intent_level', sa.String(length=10), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('draft_message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('suggested', 'accepted', 'dismissed', name='suggestionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_suggestions_agent_id'), 'ai_suggestions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_ai_suggestions_client_id'), 'ai_suggestions', ['client_id'], unique=False)
    op.create_index(op.f('ix_ai_suggestions_lead_id'), 'ai_suggestions', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_suggestions_lead_id'), table_name='ai_suggestions')
    op.drop_index(op.f('ix_ai_suggestions_client_id'), table_name='ai_suggestions')
    op.drop_index(op.f('ix_ai_suggestions_agent_id'), table_name='ai_suggestions')
    op.drop_table('ai_suggestions')
    # ### end Alembic commands ###
