"""initial schema

Revision ID: 8e9937cee674
Revises: 
Create Date: 2026-09-27 02:25:20.463812
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8e9937cee674'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('region_name', sa.String(length=120), nullable=False),
    sa.Column('region_type', sa.String(length=20), nullable=False),
    sa.Column('state_name', sa.String(length=10), nullable=True),
    sa.Column('size_rank', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('inventory', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'month', name='uq_region_month')
    )
    op.create_index(op.f('ix_market_inventory_month'), 'market_inventory', ['month'], unique=False)
    op.create_index(op.f('ix_market_inventory_region_id'), 'market_inventory', ['region_id'], unique=False)
    op.create_index(op.f('ix_market_inventory_region_name'), 'market_inventory', ['region_name'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_ref', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('for_sale', 'sold', 'ready_to_build', 'off_market', name='propertystatus', native_enum=False, length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('house_size_sqft', sa.Integer(), nullable=True),
    sa.Column('acre_lot', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('street_address', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=5), nullable=False),
    sa.Column('property_type', sa.String(length=40), nullable=True),
    sa.Column('prev_sold_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_price'), 'properties', ['price'], unique=False)
    op.create_index(op.f('ix_properties_source_ref'), 'properties', ['source_ref'], unique=False)
    op.create_index(op.f('ix_properties_state'), 'properties', ['state'], unique=False)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.create_index(op.f('ix_properties_zip_code'), 'properties', ['zip_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('agent', 'admin', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('client_type', sa.Enum('buyer', 'seller', 'both', name='clienttype', native_enum=False, length=20), nullable=False),
    sa.Column('budget_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_confirmed', sa.Boolean(), nullable=False),
    sa.Column('preferred_city', sa.String(length=100), nullable=True),
    sa.Column('preferred_state', sa.String(length=50), nullable=True),
    sa.Column('preferred_zip', sa.String(length=5), nullable=True),
    sa.Column('min_bedrooms', sa.Integer(), nullable=True),
    sa.Column('min_bathrooms', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('min_house_size_sqft', sa.Integer(), nullable=True),
    sa.Column('preferred_property_type', sa.String(length=40), nullable=True),
    sa.Column('financing_status', sa.Enum('unknown', 'not_started', 'pre_qualified', 'pre_approved', 'cash', name='financingstatus', native_enum=False, length=20), nullable=False),
    sa.Column('purchase_timeline_months', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_agent_id'), 'clients', ['agent_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('appointment_type', sa.Enum('viewing', 'meeting', 'follow_up', name='appointmenttype', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', 'no_show', name='appointmentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_agent_id'), 'appointments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_appointments_client_id'), 'appointments', ['client_id'], unique=False)
    op.create_index(op.f('ix_appointments_property_id'), 'appointments', ['property_id'], unique=False)
    op.create_index(op.f('ix_appointments_starts_at'), 'appointments', ['starts_at'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.Enum('call', 'email', 'text', 'meeting', 'note', name='interactiontype', native_enum=False, length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_agent_id'), 'interactions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_interactions_client_id'), 'interactions', ['client_id'], unique=False)
    op.create_index(op.f('ix_interactions_occurred_at'), 'interactions', ['occurred_at'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('new', 'contacted', 'qualified', 'proposal', 'negotiation', 'won', 'lost', name='leadstage', native_enum=False, length=20), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('lost_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_agent_id'), 'leads', ['agent_id'], unique=False)
    op.create_index(op.f('ix_leads_client_id'), 'leads', ['client_id'], unique=False)
    op.create_index(op.f('ix_leads_stage'), 'leads', ['stage'], unique=False)
    op.create_table('property_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('interest_level', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_interests_client_id'), 'property_interests', ['client_id'], unique=False)
    op.create_index(op.f('ix_property_interests_property_id'), 'property_interests', ['property_id'], unique=False)
    op.create_table('lead_stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.Enum('new', 'contacted', 'qualified', 'proposal', 'negotiation', 'won', 'lost', name='leadstage', native_enum=False, length=20), nullable=True),
    sa.Column('to_stage', sa.Enum('new', 'contacted', 'qualified', 'proposal', 'negotiation', 'won', 'lost', name='leadstage', native_enum=False, length=20), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_stage_history_lead_id'), 'lead_stage_history', ['lead_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'countered', 'accepted', 'rejected', 'withdrawn', name='offerstatus', native_enum=False, length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_client_id'), 'offers', ['client_id'], unique=False)
    op.create_index(op.f('ix_offers_lead_id'), 'offers', ['lead_id'], unique=False)
    op.create_index(op.f('ix_offers_property_id'), 'offers', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_property_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_lead_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_client_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_lead_stage_history_lead_id'), table_name='lead_stage_history')
    op.drop_table('lead_stage_history')
    op.drop_index(op.f('ix_property_interests_property_id'), table_name='property_interests')
    op.drop_index(op.f('ix_property_interests_client_id'), table_name='property_interests')
    op.drop_table('property_interests')
    op.drop_index(op.f('ix_leads_stage'), table_name='leads')
    op.drop_index(op.f('ix_leads_client_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_agent_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_interactions_occurred_at'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_client_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_agent_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_appointments_starts_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_property_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_client_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_agent_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_clients_agent_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_properties_zip_code'), table_name='properties')
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_state'), table_name='properties')
    op.drop_index(op.f('ix_properties_source_ref'), table_name='properties')
    op.drop_index(op.f('ix_properties_price'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_market_inventory_region_name'), table_name='market_inventory')
    op.drop_index(op.f('ix_market_inventory_region_id'), table_name='market_inventory')
    op.drop_index(op.f('ix_market_inventory_month'), table_name='market_inventory')
    op.drop_table('market_inventory')
    # ### end Alembic commands ###
